source 'https://github.com/CocoaPods/Specs.git'

target 'APCompositeFRC', :exclusive => true do
  pod "APCompositeFRC", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "APCompositeFRC", :path => "../"

  
end
